import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { AlertController, ToastController } from '@ionic/angular';
import { Category, InventoryItem, StockStatus } from '../../models/item.model';
import { InventoryService } from '../../services/inventory.service';

/**
 * EditPage responsibilities:
 * - Load a record only when the full item name matches exactly.
 * - Show a preview card before the user edits or deletes anything.
 * - Protect database-generated item IDs from manual changes.
 * - Confirm destructive deletion with an Ionic alert.
 */

@Component({
  selector: 'app-edit',
  templateUrl: './edit.page.html',
  styleUrls: ['./edit.page.scss'],
  standalone: false
})
export class EditPage implements OnInit {
  // Search input used to load an item before editing.
  searchName = '';

  // Reactive edit form bound to Ionic inputs and selects.
  itemForm!: FormGroup;

  // Indicates whether a valid record is currently loaded into the form.
  itemLoaded = false;

  // Preserves the original API lookup key when the user renames an item.
  originalItemName = '';

  // Shared loading flag for search, update, and delete operations.
  processing = false;

  // Current item is shown in the preview card above the edit form.
  currentItem: InventoryItem | null = null;

  // Search state flags control the empty and not-found messages.
  searchAttempted = false;
  searchNotFound = false;
  notFoundMessage = '';

  // Select options are derived from enums to avoid duplicated strings.
  categories = Object.values(Category);
  stockStatuses = Object.values(StockStatus);

  readonly helpMessage =
    'Search by the full item name, review the loaded record, then update or delete it. The Item ID remains read-only because it is generated by the database.';

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private inventoryService: InventoryService,
    private alertController: AlertController,
    private toastController: ToastController
  ) {}

  /**
   * Creates the edit form and listens for item names passed from other tabs.
   * This supports a smooth workflow: Inventory card -> Manage page -> loaded form.
   */
  ngOnInit(): void {
    this.initForm();

    // Query parameters are used when a user taps Manage from an inventory card.
    this.route.queryParamMap.subscribe((params) => {
      // The "name" parameter stores the exact item name to preload.
      const itemName = params.get('name');
      // Avoid reloading the same item if the page receives duplicate navigation events.
      if (itemName && itemName !== this.searchName) {
        this.searchName = itemName;
        this.searchItem();
      }
    });
  }

  /**
   * Defines the edit form fields and validation rules.
   * The item ID is disabled because the database controls that primary key.
   */
  initForm(): void {
    this.itemForm = this.fb.group({
      // Disabled controls are visible but protected from accidental editing.
      itemId: [{ value: '', disabled: true }],
      // Item name uses varchar-style validation and remains required for update requests.
      itemName: ['', [Validators.required, Validators.maxLength(100), Validators.pattern(/^[a-zA-Z0-9 '\-]+$/)]],
      // Category is controlled by ion-select, but a required validator still protects the form.
      category: ['', [Validators.required]],
      // Quantity is restricted to integer stock counts.
      quantity: [0, [Validators.required, Validators.min(0), Validators.pattern(/^\d+$/)]],
      // Price accepts a decimal value with up to two places.
      price: [0, [Validators.required, Validators.min(0), Validators.pattern(/^\d+(\.\d{1,2})?$/)]],
      supplierName: ['', [Validators.required, Validators.maxLength(100), Validators.pattern(/^[a-zA-Z0-9 '&\-]+$/)]],
      // Stock status remains editable as a first-class inventory property.
      stockStatus: ['', [Validators.required]],
      // Featured toggle remains editable when managing an existing item.
      featuredToggle: [false],
      // Notes stay optional but limited to protect card layout on phones.
      specialNote: ['', [Validators.maxLength(300)]]
    });
  }

  /**
   * Starts a full-name search from the Manage page search panel.
   */
  searchItem(): void {
    // Trim whitespace so accidental spaces do not cause failed searches.
    const name = this.searchName.trim();

    if (!name) {
      this.presentToast('Please enter an item name to search.');
      return;
    }

    // These flags let the template display the correct not-found or edit state.
    this.searchAttempted = true;
    this.searchNotFound = false;
    this.notFoundMessage = '';
    this.loadItemByName(name, true);
  }

  /**
   * Loads an item and patches the form if the API result exactly matches the name.
   * The extra exact check prevents confusing partial or unexpected server matches.
   */
  private loadItemByName(name: string, showSuccessToast: boolean): void {
    // One processing flag disables risky actions while the API call is running.
    this.processing = true;

    this.inventoryService.getItemByName(name).subscribe({
      next: (item) => {
        this.processing = false;

        // The server response is accepted only when the returned name exactly matches.
        if (this.normalizeName(item.itemName) !== this.normalizeName(name)) {
          this.handleItemNotFound(name);
          return;
        }

        // Clear any previous not-found state once a valid record is loaded.
        this.searchNotFound = false;
        this.notFoundMessage = '';
        this.itemLoaded = true;
        // currentItem powers the preview card displayed above the form.
        this.currentItem = item;
        this.originalItemName = item.itemName;
        this.searchName = item.itemName;

        // Patch values rather than rebuilding the form, preserving validators.
        // Each API field is copied into its matching form control.
        this.itemForm.patchValue({
          itemId: item.itemId ?? '',
          itemName: item.itemName,
          category: item.category,
          quantity: item.quantity,
          price: item.price,
          supplierName: item.supplierName,
          stockStatus: item.stockStatus,
          // Convert API numeric flag into a boolean value for ion-toggle.
          featuredToggle: Number(item.featuredItem) === 1,
          specialNote: item.specialNote || ''
        });

        if (showSuccessToast) {
          this.presentToast('Item loaded successfully.');
        }
      },
      error: (err) => {
        this.processing = false;
        this.handleItemNotFound(name);
        this.presentToast(this.inventoryService.toUserMessage(err, 'Item not found.'));
      }
    });
  }

  /**
   * Resets the edit workspace into a clear not-found state.
   */
  private handleItemNotFound(name: string): void {
    // Clearing itemLoaded hides the edit form so users cannot update stale data.
    this.itemLoaded = false;
    this.currentItem = null;
    this.searchNotFound = true;
    this.notFoundMessage = 'No record found for "' + name + '".';
  }

  /**
   * Normalises names for exact matching while ignoring case and outer spaces.
   */
  private normalizeName(value: string | undefined | null): string {
    // Case-insensitive comparison improves usability while still requiring full-name match.
    return String(value || '').trim().toLowerCase();
  }

  /**
   * Validates and sends the updated item to the API.
   */
  updateItem(): void {
    if (!this.itemLoaded) {
      this.presentToast('Please search for an item first.');
      return;
    }

    if (this.itemForm.invalid) {
      // Mark all fields so users immediately see what must be fixed.
      this.itemForm.markAllAsTouched();
      this.presentToast('Please fix validation errors before updating.');
      return;
    }

    this.processing = true;

    // getRawValue is required because itemId is disabled but still displayed.
    const formValue = this.itemForm.getRawValue();
    const updatedItem: InventoryItem = {
      // getRawValue includes the disabled itemId field for completeness.
      itemId: formValue.itemId ? Number(formValue.itemId) : undefined,
      itemName: formValue.itemName.trim(),
      // Category and status are already controlled by Ionic selects.
      category: formValue.category,
      // Numeric form values are cast before creating the API model.
      quantity: Number(formValue.quantity),
      price: Number(formValue.price),
      supplierName: formValue.supplierName.trim(),
      stockStatus: formValue.stockStatus,
      // Convert ion-toggle state back to the server's numeric flag format.
      featuredItem: formValue.featuredToggle ? 1 : 0,
      specialNote: formValue.specialNote?.trim() || ''
    };

    // oldName is the API lookup key; newName is the potentially edited value.
    const oldName = this.originalItemName.trim();
    const newName = updatedItem.itemName.trim();

    this.inventoryService.updateItem(oldName, updatedItem).subscribe({
      next: (message) => {
        this.processing = false;
        this.originalItemName = newName;
        this.searchName = newName;
        this.presentToast(`Success: "${newName}" has been updated.`, 'success');
        // Reload the item to keep the preview card synced with the server state.
        this.loadItemByName(newName, false);
      },
      error: (err) => {
        this.processing = false;
        this.presentToast(this.inventoryService.toUserMessage(err, 'Failed to update item.'));
      }
    });
  }

  /**
   * Opens a destructive action confirmation before deleting the record.
   */
  async deleteItem(): Promise<void> {
    if (!this.itemLoaded) {
      this.presentToast('Please search for an item first.');
      return;
    }

    // The current form name is shown in the confirmation message for clarity.
    const currentName = this.itemForm.getRawValue().itemName?.trim();

    const alert = await this.alertController.create({
      header: 'Delete inventory record?',
      message: `This will remove "${currentName}" from the shared server database.`,
      // The destructive role gives Ionic the correct visual treatment on mobile.
      buttons: [
        {
          text: 'Cancel',
          // Cancel simply closes the alert and leaves the record unchanged.
          role: 'cancel'
        },
        {
          text: 'Delete',
          role: 'destructive',
          // The destructive handler delegates actual deletion to a separate method.
          handler: () => this.confirmDelete(currentName)
        }
      ]
    });

    await alert.present();
  }

  /**
   * Performs the delete request after the user confirms the alert.
   */
  private confirmDelete(currentName: string): void {
    // Assessment API rule: Laptop must not be deleted.
    if (currentName === 'Laptop') {
      this.presentToast('Laptop cannot be deleted according to the server rule.');
      return;
    }

    // Delete requests use the original name to target the record that was loaded.
    this.processing = true;

    this.inventoryService.deleteItem(this.originalItemName).subscribe({
      next: (message) => {
        this.processing = false;
        this.presentToast(`Success: "${currentName}" has been deleted.`, 'success');
        this.resetFormState();
      },
      error: (err) => {
        this.processing = false;
        this.presentToast(this.inventoryService.toUserMessage(err, 'Failed to delete item.'));
      }
    });
  }

  /**
   * Clears every search and edit state for a fresh Manage page session.
   */
  resetFormState(): void {
    this.itemLoaded = false;
    this.currentItem = null;
    this.originalItemName = '';
    this.searchName = '';
    this.searchAttempted = false;
    this.searchNotFound = false;
    this.notFoundMessage = '';
    // Reset values match the Add form defaults so the app feels consistent.
    this.itemForm.reset({
      itemId: '',
      itemName: '',
      category: '',
      quantity: 0,
      price: 0,
      supplierName: '',
      stockStatus: StockStatus.InStock,
      // Default toggle state matches the Add form default.
      featuredToggle: false,
      specialNote: ''
    });
  }

  /**
   * Maps stock status to a chip class used by the preview card.
   */
  statusClass(item: InventoryItem): string {
    if (item.stockStatus === StockStatus.LowStock) {
      return 'status-low';
    }

    if (item.stockStatus === StockStatus.OutOfStock) {
      return 'status-out';
    }

    return 'status-in';
  }

  /**
   * Returns true when a form control should show its validation message.
   */
  isInvalid(controlName: string): boolean {
    // FormGroup#get returns null if the name is mistyped, so check safely.
    const control = this.itemForm.get(controlName);
    return !!control && control.invalid && (control.dirty || control.touched);
  }

  /**
   * Converts validator errors into user-friendly English feedback.
   */
  fieldError(controlName: string): string {
    const control = this.itemForm.get(controlName);

    // No errors means the template should not display any validation text.
    if (!control || !control.errors) {
      return '';
    }

    if (control.errors['required']) {
      return 'This field is required.';
    }

    if (control.errors['min']) {
      return 'Value must be 0 or greater.';
    }

    if (control.errors['pattern']) {
      return controlName === 'quantity' || controlName === 'price'
        ? (controlName === 'price' ? 'Use a valid price, for example 12 or 12.50.' : 'Use whole numbers only.')
        : 'Use letters, numbers, spaces, apostrophes or hyphens only.';
    }

    if (control.errors['maxlength']) {
      return 'This value is too long.';
    }

    return 'Please check this field.';
  }

  /**
   * Shared toast helper for search, update, and delete feedback.
   * Success toasts use Ionic's success color so write actions feel confirmed.
   */
  async presentToast(message: string, color: string = 'medium'): Promise<void> {
    // Toasts are non-blocking, which is suitable for frequent CRUD feedback.
    const toast = await this.toastController.create({
      message,
      duration: 2600,
      position: 'bottom',
      color,
      buttons: [
        {
          text: 'OK',
          role: 'cancel'
        }
      ]
    });

    await toast.present();
  }
}
