import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ToastController } from '@ionic/angular';
import { Category, InventoryItem, StockStatus } from '../../models/item.model';
import { InventoryService } from '../../services/inventory.service';

/**
 * AddPage responsibilities:
 * - Collect new inventory values through Ionic form elements.
 * - Validate text, integer, decimal, enum, and optional-note fields.
 * - Convert toggle and numeric values into the API-compatible model.
 * - Refresh the featured showcase after successful creation.
 */

@Component({
  selector: 'app-add',
  templateUrl: './add.page.html',
  styleUrls: ['./add.page.scss'],
  standalone: false
})
export class AddPage implements OnInit {
  // Reactive form instance used by the Ionic form controls in the template.
  itemForm!: FormGroup;

  // Featured items are displayed below the add form using the same card style as Tab 1.
  featuredItems: InventoryItem[] = [];

  // Separate loading states keep the form and showcase feedback independent.
  submitting = false;
  loadingFeatured = false;

  // Enum values are converted to arrays so ion-select can render them safely.
  categories = Object.values(Category);
  stockStatuses = Object.values(StockStatus);

  // The help widget reads this text and shows it in a mobile-friendly alert.
  readonly helpMessage =
    'Create a new inventory record. The Item ID is generated by the database, item names must be unique, and featured items appear in the showcase below.';

  constructor(
    private fb: FormBuilder,
    private inventoryService: InventoryService,
    private toastController: ToastController,
    private router: Router
  ) {}

  /**
   * Initialises the form once Angular creates the page.
   * Data loading is kept in ionViewWillEnter so the showcase refreshes whenever
   * the user returns from another tab.
   */
  ngOnInit(): void {
    this.initForm();
  }

  /**
   * Ionic lifecycle hook called each time the Add tab becomes active.
   * This keeps the featured showcase up to date after edits or deletes.
   */
  ionViewWillEnter(): void {
    this.loadFeaturedItems();
  }

  /**
   * Builds the reactive form and validation rules.
   * Validation happens before API calls so incorrect input never reaches the server.
   */
  initForm(): void {
    this.itemForm = this.fb.group({
      // Item names are unique and limited to safe text characters.
      itemName: ['', [Validators.required, Validators.maxLength(100), Validators.pattern(/^[a-zA-Z0-9 '\-]+$/)]],
      // The user must pick one valid category from the action-sheet select.
      category: ['', [Validators.required]],
      // Quantity must be a whole number because inventory counts cannot be fractional.
      quantity: [0, [Validators.required, Validators.min(0), Validators.pattern(/^\d+$/)]],
      // Price accepts numbers with up to two decimal places for currency-style values.
      price: [0, [Validators.required, Validators.min(0), Validators.pattern(/^\d+(\.\d{1,2})?$/)]],
      // Supplier name is a required varchar-style field.
      supplierName: ['', [Validators.required, Validators.maxLength(100), Validators.pattern(/^[a-zA-Z0-9 '&\-]+$/)]],
      // Defaulting to In Stock reduces friction while keeping the field visible.
      stockStatus: [StockStatus.InStock, [Validators.required]],
      // The toggle maps to the API's featured_item 0/1 field on submit.
      featuredToggle: [false],
      // Notes are optional but capped to protect card layout readability.
      specialNote: ['', [Validators.maxLength(300)]]
    });
  }

  /**
   * Loads featured items for the showcase section.
   * Sorting by item name creates a predictable mobile browsing experience.
   */
  loadFeaturedItems(): void {
    this.loadingFeatured = true;

    this.inventoryService.getFeaturedItems().subscribe({
      next: (data) => {
        // Sorting after load avoids changing the service output for other callers.
        this.featuredItems = data.sort((a, b) => a.itemName.localeCompare(b.itemName));
        this.loadingFeatured = false;
      },
      error: (err) => {
        this.loadingFeatured = false;
        // Service-level error mapping keeps API failures understandable.
        this.presentToast(this.inventoryService.toUserMessage(err, 'Failed to load featured items.'));
      }
    });
  }

  /**
   * Validates, transforms, and submits the add form.
   * Page code stays focused on UX while InventoryService handles API formatting.
   */
  submitForm(): void {
    if (this.itemForm.invalid) {
      // Touching all controls reveals validation messages in one clear pass.
      this.itemForm.markAllAsTouched();
      this.presentToast('Please complete the required fields and fix validation errors.');
      return;
    }

    this.submitting = true;

    const formValue = this.itemForm.value;
    const newItem: InventoryItem = {
      // Trim text fields before sending them to keep the shared database clean.
      itemName: formValue.itemName.trim(),
      // Select fields already contain enum-safe values.
      category: formValue.category,
      // Number conversion is repeated here to make the submitted object explicit.
      quantity: Number(formValue.quantity),
      // Decimal input is stored as a number for the API contract.
      price: Number(formValue.price),
      supplierName: formValue.supplierName.trim(),
      // Stock status remains user controlled instead of auto-generated.
      stockStatus: formValue.stockStatus,
      featuredItem: formValue.featuredToggle ? 1 : 0,
      specialNote: formValue.specialNote?.trim() || ''
    };

    this.inventoryService.addItem(newItem).subscribe({
      next: (message) => {
        this.submitting = false;
        this.presentToast(`Success: "${newItem.itemName}" has been added.`, 'success');
        this.resetForm();
        // Refresh the showcase so a newly featured item appears immediately.
        this.loadFeaturedItems();
      },
      error: (err) => {
        this.submitting = false;
        this.presentToast(
          this.inventoryService.toUserMessage(err, 'Failed to add item. Check the unique item name and field values.')
        );
      }
    });
  }

  /**
   * Restores the form to a clean state without navigating away from the tab.
   */
  resetForm(): void {
    this.itemForm.reset({
      // Reset all user-entered values and return controls to their default state.
      itemName: '',
      category: '',
      quantity: 0,
      price: 0,
      supplierName: '',
      stockStatus: StockStatus.InStock,
      featuredToggle: false,
      specialNote: ''
    });
  }

  /**
   * Sends the selected featured card to the Manage tab.
   * Query parameters let EditPage preload the selected record automatically.
   */
  manageItem(item: InventoryItem): void {
    this.router.navigate(['/tabs/edit'], {
      queryParams: { name: item.itemName }
    });
  }

  /**
   * Chooses the visual chip class for each stock status.
   */
  statusClass(item: InventoryItem): string {
    if (item.stockStatus === StockStatus.LowStock) {
      return 'status-low';
    }

    if (item.stockStatus === StockStatus.OutOfStock) {
      return 'status-out';
    }

    return 'status-in';
  }

  /**
   * Shows validation messages only after the user interacts with a field.
   */
  isInvalid(controlName: string): boolean {
    const control = this.itemForm.get(controlName);
    return !!control && control.invalid && (control.dirty || control.touched);
  }

  /**
   * Converts Angular validator results into clear field-level messages.
   */
  fieldError(controlName: string): string {
    const control = this.itemForm.get(controlName);

    if (!control || !control.errors) {
      return '';
    }

    if (control.errors['required']) {
      return 'This field is required.';
    }

    if (control.errors['min']) {
      return 'Value must be 0 or greater.';
    }

    if (control.errors['pattern']) {
      return controlName === 'quantity' || controlName === 'price'
        ? (controlName === 'price' ? 'Use a valid price, for example 12 or 12.50.' : 'Use whole numbers only.')
        : 'Use letters, numbers, spaces, apostrophes or hyphens only.';
    }

    if (control.errors['maxlength']) {
      return 'This value is too long.';
    }

    return 'Please check this field.';
  }

  /**
   * Improves ngFor rendering by giving Angular a stable card identity.
   */
  trackByItemName(index: number, item: InventoryItem): string {
    return item.itemName || String(index);
  }

  /**
   * Central toast helper for AddPage feedback.
   * The optional color makes successful CRUD actions easier to notice on mobile.
   */
  async presentToast(message: string, color: string = 'medium'): Promise<void> {
    const toast = await this.toastController.create({
      message,
      duration: 2600,
      position: 'bottom',
      color,
      buttons: [
        {
          text: 'OK',
          role: 'cancel'
        }
      ]
    });

    await toast.present();
  }
}
